version: "2"
services:
  szondi-aggregator:
    image: golang:1.8
    volumes:
    - .:/go/src/github.com/vavas/Szondi-Aggregator
    working_dir: /go/src/github.com/vavas/Szondi-Aggregator
    command: ./dist/szondi-aggregator
    expose:
    - 80
    environment:
      PROJECT_NAME: szondi-aggregator
      CORS_ALLOWED_ORIGINS: "*"