version: '2'
networks:
  microservices:
    external: true
services:
  szondi-aggregator:
    networks:
    - microservices
    expose:
    - 80
    ports:
    - 5777:80
    environment:
      ENGINE_RPC_DSN: szondi-engine:8080
